### ISSUE TITLE
Error: No named parameter with the name 'navigatorKey'.

### ISSUE THREAD

**Issue by llorenzo** [praween-link/flutter_sfs#1]
I'm using a Router instead of a Navigator since I use the outo route package

           return MaterialApp.router(
                routerDelegate: _appRouter.delegate()
              );

How to get the navigatorKey in here?

**Comment by praween-link** [comment]
Now, no need to pass `navigatorKey`, on the latest version >= v1.0.0

Thanks @llorenzo.
